template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "russ1264"
__REPO__ = "lang-bxr"
__UND2C__ = "bxr"
__UNDEFINED__ = "Russia Buriat"
__UND__ = "bxr"
