template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "russ1264"
__REPO__ = "lang-bxr"
__UND2C__ = "bxr"
__UNDEFINED__ = "Russia Buriat"
__UND__ = "bxr"
