template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "russ1264"
__REPO__ = "lang-bxr"
__UND2C__ = "bxr"
__UNDEFINED__ = "Russia Buriat"
__UND__ = "bxr"
